"""End-to-end optimization pipeline for unsloth/Qwen3.5-0.8B ONNX models.

All ONNX graph transformations (Gemm->MatMul, Cast chain elimination,
INT4 quantization) are handled by Olive passes declared in the JSON configs.
This script orchestrates the three Olive runs and writes the GenAI runtime
configuration files.

Architecture notes:
  - Vision encoder  : ViT with absolute pos embed + rotary + PatchMerger (ONNX-safe).
  - Text decoder    : Hybrid Gated DeltaNet (3:1 DeltaNet/standard attention).
                      NOT exported via custom model — ModelBuilder handles it.
  - Embedding model : embed_tokens + image feature scatter (ONNX-safe).

Preprocessing (from preprocessor_config.json):
  - image_mean / image_std : [0.5, 0.5, 0.5]
  - rescale_factor         : 1/255
  - patch_size             : 16
  - spatial_merge_size     : 2
  - temporal_patch_size    : 2
  - min_pixels             : loaded from preprocessor_config (size.shortest_edge)
  - max_pixels             : loaded from preprocessor_config (size.longest_edge)

Usage:
    python optimize.py --config-dir cpu_and_mobile --device cpu
    python optimize.py --config-dir cuda --device gpu
    python optimize.py --config-dir cpu_and_mobile --skip-export
"""
import argparse
import json
import logging
from pathlib import Path

logging.getLogger("onnxscript").setLevel(logging.WARNING)
logging.getLogger("onnx_ir").setLevel(logging.WARNING)

MODELS_DIR = "models"

# Preprocessing values verified against unsloth/Qwen3.5-0.8B preprocessor_config.json
# NOTE: min_pixels / max_pixels are derived from size.shortest_edge / size.longest_edge
# since the preprocessor_config uses the `size` field instead of explicit pixel bounds.
# Update these if you target a different Qwen3.5-VL variant.
_PREPROCESSOR = {
    "patch_size": 16,
    "merge_size": 2,
    "temporal_patch_size": 2,
    "image_mean": [0.5, 0.5, 0.5],
    "image_std": [0.5, 0.5, 0.5],
    "rescale_factor": 0.00392156862745098,   # 1/255
    # size.shortest_edge and size.longest_edge from preprocessor_config.json
    # Replace with actual values once confirmed from the gated model card.
    "min_pixels": 65536,       # 256*256  — placeholder; verify against your model
    "max_pixels": 16777216,    # 4096*4096 — placeholder; verify against your model
}

# Token IDs (same as Qwen3-VL base)
_TOKEN_IDS = {
    "image_token_id":       151655,
    "video_token_id":       151656,
    "vision_start_token_id": 151652,
}


# =============================================================================
# 1. Olive Export + Optimization + Quantization
# =============================================================================

def export_models(config_dir: str):
    """Run Olive for all 3 sub-models (embedding, text, vision)."""
    from olive import run

    config_path = Path(config_dir)
    print(f"=== Running Olive pipelines (configs from {config_path}) ===")
    for config in ("embedding.json", "text.json", "vision.json"):
        print(f"  Running {config}...")
        run(str(config_path / config))
    print()


# =============================================================================
# 2. GenAI Runtime Config Generation
# =============================================================================

def update_genai_config(output_dir: str = MODELS_DIR, device: str = "cpu"):
    """Patch genai_config.json with embedding/vision sections and processor_config.

    genai_config.json is generated by ModelBuilder (text.json pass).
    We add the embedding and vision sub-model entries so the ORT GenAI runtime
    can locate and call them at inference time.
    """
    config_path = Path(output_dir) / "genai_config.json"
    with open(config_path) as f:
        config = json.load(f)

    # Provider options
    if device == "gpu":
        provider_options = [
            {"cuda": {"enable_cuda_graph": "0", "enable_skip_layer_norm_strict_mode": "1"}}
        ]
    else:
        provider_options = []

    session_options = {"log_id": "onnxruntime-genai", "provider_options": provider_options}

    # Embedding sub-model
    config["model"]["embedding"] = {
        "filename": "embedding.onnx",
        "inputs":  {"input_ids": "input_ids", "image_features": "image_features"},
        "outputs": {"inputs_embeds": "inputs_embeds"},
        "session_options": session_options,
    }

    # Vision sub-model
    # window_size: Qwen3.5-VL uses the same ViT architecture as Qwen3-VL.
    # Verify against vision_config if a non-standard window size is used.
    config["model"]["vision"] = {
        "filename": "vision.onnx",
        "config_filename": "processor_config.json",
        "spatial_merge_size": _PREPROCESSOR["merge_size"],
        "tokens_per_second": 2.0,
        "patch_size": _PREPROCESSOR["patch_size"],
        "window_size": 64,   # standard for Qwen3-VL family; verify for Qwen3.5-VL
        "inputs":  {"pixel_values": "pixel_values", "image_grid_thw": "image_grid_thw"},
        "outputs": {"image_features": "image_features"},
        "session_options": session_options,
    }

    config["model"]["image_token_id"]        = _TOKEN_IDS["image_token_id"]
    config["model"]["video_token_id"]        = _TOKEN_IDS["video_token_id"]
    config["model"]["vision_start_token_id"] = _TOKEN_IDS["vision_start_token_id"]

    # Fix null search params (can appear in ModelBuilder output)
    if config["search"].get("top_k") is None:
        config["search"]["top_k"] = 50
    if config["search"].get("top_p") is None:
        config["search"]["top_p"] = 1.0

    with open(config_path, "w") as f:
        json.dump(config, f, indent=4)
    print(f"  Updated {config_path}")

    # Create processor_config.json
    # All values verified against unsloth/Qwen3.5-0.8B preprocessor_config.json.
    # min_pixels / max_pixels come from size.shortest_edge / size.longest_edge.
    processor_config = {
        "processor": {
            "name": "qwen3_5_vl_image_processor",
            "transforms": [
                {"operation": {"name": "decode_image",   "type": "DecodeImage",  "attrs": {"color_space": "RGB"}}},
                {"operation": {"name": "convert_to_rgb", "type": "ConvertRGB"}},
                {"operation": {"name": "resize", "type": "Resize", "attrs": {
                    "width": 540, "height": 360,
                    "smart_resize": 1,
                    "min_pixels": _PREPROCESSOR["min_pixels"],
                    "max_pixels": _PREPROCESSOR["max_pixels"],
                    "patch_size": _PREPROCESSOR["patch_size"],
                    "merge_size": _PREPROCESSOR["merge_size"],
                }}},
                {"operation": {"name": "rescale", "type": "Rescale", "attrs": {
                    "rescale_factor": _PREPROCESSOR["rescale_factor"],
                }}},
                {"operation": {"name": "normalize", "type": "Normalize", "attrs": {
                    "mean": _PREPROCESSOR["image_mean"],
                    "std":  _PREPROCESSOR["image_std"],
                    "qwen3_vl": 1,  # flag for ORT GenAI's Qwen3-family normalizer
                }}},
                {"operation": {"name": "patch_image", "type": "PatchImage", "attrs": {
                    "patch_size":          _PREPROCESSOR["patch_size"],
                    "temporal_patch_size": _PREPROCESSOR["temporal_patch_size"],
                    "merge_size":          _PREPROCESSOR["merge_size"],
                }}},
            ],
        }
    }

    processor_path = Path(output_dir) / "processor_config.json"
    with open(processor_path, "w") as f:
        json.dump(processor_config, f, indent=2)
    print(f"  Created {processor_path}")


# =============================================================================
# Main
# =============================================================================

def main():
    parser = argparse.ArgumentParser(description="Optimize unsloth/Qwen3.5-0.8B ONNX models")
    parser.add_argument("--device", choices=["gpu", "cpu"], default="cpu",
                        help="Target device (default: cpu)")
    parser.add_argument("--config-dir", default="cpu_and_mobile",
                        help="Directory containing Olive JSON configs (default: cpu_and_mobile)")
    parser.add_argument("--skip-export", action="store_true",
                        help="Skip Olive export (models already exist)")
    parser.add_argument("--models-dir", default=None,
                        help="Models directory (default: <config-dir>/models)")
    args = parser.parse_args()

    models_dir = args.models_dir or str(Path(args.config_dir) / MODELS_DIR)

    if not args.skip_export:
        export_models(args.config_dir)

    print("=== Generating GenAI runtime configs ===")
    update_genai_config(output_dir=models_dir, device=args.device)
    print()
    print("Done.")


if __name__ == "__main__":
    main()
